### PR TITLE
Updating for PureScript v0.7.6

### PR DESCRIPTION
**Pull request by chrisdotcode**
Also removes unused imports, tidies up some extra spaces, etc..

### CODE REVIEW

**Comment by SimonRichardson** [comment]
Thanks

**Comment by chrisdotcode** [comment]
@SimonRichardson Forgot to merge?

**Comment by chrisdotcode** [comment]
Also, we should probably update the documentation, and make sure bower points to the right version.

**Comment by SimonRichardson** [comment]
Can't merge from my phone, I'll sort it out in a bit

**Comment by chrisdotcode** [comment]
(Don't forget to remove the changing of the homepage from my version of the fork).

**Comment by SimonRichardson** [comment]
thanks again :+1:

**Comment by SimonRichardson** [comment]
fyi: if i ever get time, I want to move the library to resemble the redis library as it offers better structures.

https://github.com/dicefm/purescript-node-redis/tree/master/src/Database/Redis/Commands

**Pull request merged**
